# Generated by Django 6.0 on 2026-03-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('rdate', models.DateTimeField()),
                ('time', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.type')),
            ],
        ),
    ]
