# Generated by Django 6.0 on 2026-03-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rdate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='time',
        ),
        migrations.AlterField(
            model_name='movie',
            name='area',
            field=models.CharField(default='大陆', max_length=100),
        ),
    ]
